# Generated by Django 5.0.6 on 2024-07-07 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('form', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('price_limit_from', models.IntegerField()),
                ('price_limit_to', models.IntegerField()),
                ('online_lessons', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=100)),
                ('offline_lessons', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=100)),
                ('lessons_at_home', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=100)),
                ('date', models.DateTimeField()),
                ('level_of_knowledge', models.CharField(choices=[('Начальный', "Начальный'"), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], default='+', max_length=100)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
