# Generated by Django 5.0.6 on 2024-07-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
    ]
