# Generated by Django 5.0.6 on 2024-07-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_remove_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN'), ('RUB', 'RUB')], default='BYN', max_length=100),
        ),
    ]
