# Generated by Django 5.0.6 on 2024-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Math', 'Math'), ('History', 'History'), ('Belarusian', 'Belarusian'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], default='English', max_length=100),
        ),
    ]
